version: '3.8'

services:
  backend:
    build: ./.
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/html
    depends_on:
      - backend
    

volumes:
  nginx:
  static:
